<?xml version="1.0" encoding="utf-8"?><Database Name="dmaa0214_3Sem_2" Class="ConnectToDatabaseDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=kraka.ucn.dk;Initial Catalog=dmaa0214_3Sem_2;User ID=dmaa0214_3Sem_2" SettingsObjectName="ServerProject.Properties.Settings" SettingsPropertyName="dmaa0214_3Sem_2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Customer_Reservation" Member="Reservations" ThisKey="CusID" OtherKey="CustomerID" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.Seat" Member="Seats">
    <Type Name="Seat">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Row" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ColumnArray" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SchedulerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Scheduler_Seat" Member="Scheduler" ThisKey="SchedulerID" OtherKey="SchID" Type="Scheduler" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Hall" Member="Halls">
    <Type Name="Hall">
      <Column Name="HallID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MaxNumberOfSeats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Hall_Scheduler" Member="Schedulers" ThisKey="HallID" OtherKey="HallID" Type="Scheduler" />
    </Type>
  </Table>
  <Table Name="dbo.Movie" Member="Movies">
    <Type Name="Movie">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Playtime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Movie_Scheduler" Member="Schedulers" ThisKey="MovieID" OtherKey="MovieID" Type="Scheduler" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="ResID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchedulerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Row" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Seat" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Customer_Reservation" Member="Customer" ThisKey="CustomerID" OtherKey="CusID" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Scheduler_Reservation" Member="Scheduler" ThisKey="SchedulerID" OtherKey="SchID" Type="Scheduler" IsForeignKey="true" DeleteRule="SET DEFAULT" />
    </Type>
  </Table>
  <Table Name="dbo.Scheduler" Member="Schedulers">
    <Type Name="Scheduler">
      <Column Name="SchID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Datetime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Starttime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="MovieID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HallID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Scheduler_Seat" Member="Seats" ThisKey="SchID" OtherKey="SchedulerID" Type="Seat" />
      <Association Name="Scheduler_Reservation" Member="Reservations" ThisKey="SchID" OtherKey="SchedulerID" Type="Reservation" />
      <Association Name="Hall_Scheduler" Member="Hall" ThisKey="HallID" OtherKey="HallID" Type="Hall" IsForeignKey="true" />
      <Association Name="Movie_Scheduler" Member="Movie" ThisKey="MovieID" OtherKey="MovieID" Type="Movie" IsForeignKey="true" DeleteRule="SET DEFAULT" />
    </Type>
  </Table>
</Database>