//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PlaytimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormsClient.ServiceReference1.Scheduler[] SchedulersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieID {
            get {
                return this.MovieIDField;
            }
            set {
                if ((this.MovieIDField.Equals(value) != true)) {
                    this.MovieIDField = value;
                    this.RaisePropertyChanged("MovieID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> Playtime {
            get {
                return this.PlaytimeField;
            }
            set {
                if ((this.PlaytimeField.Equals(value) != true)) {
                    this.PlaytimeField = value;
                    this.RaisePropertyChanged("Playtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FormsClient.ServiceReference1.Scheduler[] Schedulers {
            get {
                return this.SchedulersField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulersField, value) != true)) {
                    this.SchedulersField = value;
                    this.RaisePropertyChanged("Schedulers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scheduler", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Scheduler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> StarttimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MovieIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormsClient.ServiceReference1.Seat[] SeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormsClient.ServiceReference1.Reservation[] ReservationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchID {
            get {
                return this.SchIDField;
            }
            set {
                if ((this.SchIDField.Equals(value) != true)) {
                    this.SchIDField = value;
                    this.RaisePropertyChanged("SchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.TimeSpan> Starttime {
            get {
                return this.StarttimeField;
            }
            set {
                if ((this.StarttimeField.Equals(value) != true)) {
                    this.StarttimeField = value;
                    this.RaisePropertyChanged("Starttime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> MovieID {
            get {
                return this.MovieIDField;
            }
            set {
                if ((this.MovieIDField.Equals(value) != true)) {
                    this.MovieIDField = value;
                    this.RaisePropertyChanged("MovieID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> HallID {
            get {
                return this.HallIDField;
            }
            set {
                if ((this.HallIDField.Equals(value) != true)) {
                    this.HallIDField = value;
                    this.RaisePropertyChanged("HallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FormsClient.ServiceReference1.Seat[] Seats {
            get {
                return this.SeatsField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatsField, value) != true)) {
                    this.SeatsField = value;
                    this.RaisePropertyChanged("Seats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FormsClient.ServiceReference1.Reservation[] Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsField, value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seat", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Seat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SchedulerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ColumnArray {
            get {
                return this.ColumnArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnArrayField, value) != true)) {
                    this.ColumnArrayField = value;
                    this.RaisePropertyChanged("ColumnArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> SchedulerID {
            get {
                return this.SchedulerIDField;
            }
            set {
                if ((this.SchedulerIDField.Equals(value) != true)) {
                    this.SchedulerIDField = value;
                    this.RaisePropertyChanged("SchedulerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SchedulerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResID {
            get {
                return this.ResIDField;
            }
            set {
                if ((this.ResIDField.Equals(value) != true)) {
                    this.ResIDField = value;
                    this.RaisePropertyChanged("ResID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> SchedulerID {
            get {
                return this.SchedulerIDField;
            }
            set {
                if ((this.SchedulerIDField.Equals(value) != true)) {
                    this.SchedulerIDField = value;
                    this.RaisePropertyChanged("SchedulerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Row {
            get {
                return this.RowField;
            }
            set {
                if ((object.ReferenceEquals(this.RowField, value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Seat {
            get {
                return this.SeatField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatField, value) != true)) {
                    this.SeatField = value;
                    this.RaisePropertyChanged("Seat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormsClient.ServiceReference1.Reservation[] ReservationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CusID {
            get {
                return this.CusIDField;
            }
            set {
                if ((this.CusIDField.Equals(value) != true)) {
                    this.CusIDField = value;
                    this.RaisePropertyChanged("CusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FormsClient.ServiceReference1.Reservation[] Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsField, value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetBestSeats", ReplyAction="http://tempuri.org/ICustomerService/GetBestSeatsResponse")]
        int[] GetBestSeats(int amount, int schedulerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetBestSeats", ReplyAction="http://tempuri.org/ICustomerService/GetBestSeatsResponse")]
        System.Threading.Tasks.Task<int[]> GetBestSeatsAsync(int amount, int schedulerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllMovies", ReplyAction="http://tempuri.org/ICustomerService/GetAllMoviesResponse")]
        FormsClient.ServiceReference1.Movie[] GetAllMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllMovies", ReplyAction="http://tempuri.org/ICustomerService/GetAllMoviesResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Movie[]> GetAllMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetReservationByCustomerID", ReplyAction="http://tempuri.org/ICustomerService/GetReservationByCustomerIDResponse")]
        FormsClient.ServiceReference1.Reservation[] GetReservationByCustomerID(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetReservationByCustomerID", ReplyAction="http://tempuri.org/ICustomerService/GetReservationByCustomerIDResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Reservation[]> GetReservationByCustomerIDAsync(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllSchedulers", ReplyAction="http://tempuri.org/ICustomerService/GetAllSchedulersResponse")]
        FormsClient.ServiceReference1.Scheduler[] GetAllSchedulers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllSchedulers", ReplyAction="http://tempuri.org/ICustomerService/GetAllSchedulersResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler[]> GetAllSchedulersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetSchedulerByMovieID", ReplyAction="http://tempuri.org/ICustomerService/GetSchedulerByMovieIDResponse")]
        FormsClient.ServiceReference1.Scheduler GetSchedulerByMovieID(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetSchedulerByMovieID", ReplyAction="http://tempuri.org/ICustomerService/GetSchedulerByMovieIDResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler> GetSchedulerByMovieIDAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetSchedulerByID", ReplyAction="http://tempuri.org/ICustomerService/GetSchedulerByIDResponse")]
        FormsClient.ServiceReference1.Scheduler GetSchedulerByID(int schedulerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetSchedulerByID", ReplyAction="http://tempuri.org/ICustomerService/GetSchedulerByIDResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler> GetSchedulerByIDAsync(int schedulerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/MakeReservation", ReplyAction="http://tempuri.org/ICustomerService/MakeReservationResponse")]
        void MakeReservation(string row, string seat, int schedulerID, int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/MakeReservation", ReplyAction="http://tempuri.org/ICustomerService/MakeReservationResponse")]
        System.Threading.Tasks.Task MakeReservationAsync(string row, string seat, int schedulerID, int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/MakeCustomer", ReplyAction="http://tempuri.org/ICustomerService/MakeCustomerResponse")]
        void MakeCustomer(string name, string phoneNumber, string password, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/MakeCustomer", ReplyAction="http://tempuri.org/ICustomerService/MakeCustomerResponse")]
        System.Threading.Tasks.Task MakeCustomerAsync(string name, string phoneNumber, string password, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/MakeScheduler", ReplyAction="http://tempuri.org/ICustomerService/MakeSchedulerResponse")]
        void MakeScheduler(System.DateTime date, System.TimeSpan time, int movieID, int hallID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/MakeScheduler", ReplyAction="http://tempuri.org/ICustomerService/MakeSchedulerResponse")]
        System.Threading.Tasks.Task MakeSchedulerAsync(System.DateTime date, System.TimeSpan time, int movieID, int hallID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/FindMovieByName", ReplyAction="http://tempuri.org/ICustomerService/FindMovieByNameResponse")]
        FormsClient.ServiceReference1.Movie FindMovieByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/FindMovieByName", ReplyAction="http://tempuri.org/ICustomerService/FindMovieByNameResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Movie> FindMovieByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetSchedulerListByMovieID", ReplyAction="http://tempuri.org/ICustomerService/GetSchedulerListByMovieIDResponse")]
        FormsClient.ServiceReference1.Scheduler[] GetSchedulerListByMovieID(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetSchedulerListByMovieID", ReplyAction="http://tempuri.org/ICustomerService/GetSchedulerListByMovieIDResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler[]> GetSchedulerListByMovieIDAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllAvailableSeats", ReplyAction="http://tempuri.org/ICustomerService/GetAllAvailableSeatsResponse")]
        int[][] GetAllAvailableSeats(int schID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllAvailableSeats", ReplyAction="http://tempuri.org/ICustomerService/GetAllAvailableSeatsResponse")]
        System.Threading.Tasks.Task<int[][]> GetAllAvailableSeatsAsync(int schID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerByPhone", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByPhoneResponse")]
        FormsClient.ServiceReference1.Customer GetCustomerByPhone(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerByPhone", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByPhoneResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Customer> GetCustomerByPhoneAsync(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetResByCusPhone", ReplyAction="http://tempuri.org/ICustomerService/GetResByCusPhoneResponse")]
        FormsClient.ServiceReference1.Reservation[] GetResByCusPhone(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetResByCusPhone", ReplyAction="http://tempuri.org/ICustomerService/GetResByCusPhoneResponse")]
        System.Threading.Tasks.Task<FormsClient.ServiceReference1.Reservation[]> GetResByCusPhoneAsync(string phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : FormsClient.ServiceReference1.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<FormsClient.ServiceReference1.ICustomerService>, FormsClient.ServiceReference1.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetBestSeats(int amount, int schedulerID) {
            return base.Channel.GetBestSeats(amount, schedulerID);
        }
        
        public System.Threading.Tasks.Task<int[]> GetBestSeatsAsync(int amount, int schedulerID) {
            return base.Channel.GetBestSeatsAsync(amount, schedulerID);
        }
        
        public FormsClient.ServiceReference1.Movie[] GetAllMovies() {
            return base.Channel.GetAllMovies();
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Movie[]> GetAllMoviesAsync() {
            return base.Channel.GetAllMoviesAsync();
        }
        
        public FormsClient.ServiceReference1.Reservation[] GetReservationByCustomerID(int customerID) {
            return base.Channel.GetReservationByCustomerID(customerID);
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Reservation[]> GetReservationByCustomerIDAsync(int customerID) {
            return base.Channel.GetReservationByCustomerIDAsync(customerID);
        }
        
        public FormsClient.ServiceReference1.Scheduler[] GetAllSchedulers() {
            return base.Channel.GetAllSchedulers();
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler[]> GetAllSchedulersAsync() {
            return base.Channel.GetAllSchedulersAsync();
        }
        
        public FormsClient.ServiceReference1.Scheduler GetSchedulerByMovieID(int movieID) {
            return base.Channel.GetSchedulerByMovieID(movieID);
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler> GetSchedulerByMovieIDAsync(int movieID) {
            return base.Channel.GetSchedulerByMovieIDAsync(movieID);
        }
        
        public FormsClient.ServiceReference1.Scheduler GetSchedulerByID(int schedulerID) {
            return base.Channel.GetSchedulerByID(schedulerID);
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler> GetSchedulerByIDAsync(int schedulerID) {
            return base.Channel.GetSchedulerByIDAsync(schedulerID);
        }
        
        public void MakeReservation(string row, string seat, int schedulerID, int customerID) {
            base.Channel.MakeReservation(row, seat, schedulerID, customerID);
        }
        
        public System.Threading.Tasks.Task MakeReservationAsync(string row, string seat, int schedulerID, int customerID) {
            return base.Channel.MakeReservationAsync(row, seat, schedulerID, customerID);
        }
        
        public void MakeCustomer(string name, string phoneNumber, string password, string mail) {
            base.Channel.MakeCustomer(name, phoneNumber, password, mail);
        }
        
        public System.Threading.Tasks.Task MakeCustomerAsync(string name, string phoneNumber, string password, string mail) {
            return base.Channel.MakeCustomerAsync(name, phoneNumber, password, mail);
        }
        
        public void MakeScheduler(System.DateTime date, System.TimeSpan time, int movieID, int hallID) {
            base.Channel.MakeScheduler(date, time, movieID, hallID);
        }
        
        public System.Threading.Tasks.Task MakeSchedulerAsync(System.DateTime date, System.TimeSpan time, int movieID, int hallID) {
            return base.Channel.MakeSchedulerAsync(date, time, movieID, hallID);
        }
        
        public FormsClient.ServiceReference1.Movie FindMovieByName(string name) {
            return base.Channel.FindMovieByName(name);
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Movie> FindMovieByNameAsync(string name) {
            return base.Channel.FindMovieByNameAsync(name);
        }
        
        public FormsClient.ServiceReference1.Scheduler[] GetSchedulerListByMovieID(int movieID) {
            return base.Channel.GetSchedulerListByMovieID(movieID);
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Scheduler[]> GetSchedulerListByMovieIDAsync(int movieID) {
            return base.Channel.GetSchedulerListByMovieIDAsync(movieID);
        }
        
        public int[][] GetAllAvailableSeats(int schID) {
            return base.Channel.GetAllAvailableSeats(schID);
        }
        
        public System.Threading.Tasks.Task<int[][]> GetAllAvailableSeatsAsync(int schID) {
            return base.Channel.GetAllAvailableSeatsAsync(schID);
        }
        
        public FormsClient.ServiceReference1.Customer GetCustomerByPhone(string phone) {
            return base.Channel.GetCustomerByPhone(phone);
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Customer> GetCustomerByPhoneAsync(string phone) {
            return base.Channel.GetCustomerByPhoneAsync(phone);
        }
        
        public FormsClient.ServiceReference1.Reservation[] GetResByCusPhone(string phone) {
            return base.Channel.GetResByCusPhone(phone);
        }
        
        public System.Threading.Tasks.Task<FormsClient.ServiceReference1.Reservation[]> GetResByCusPhoneAsync(string phone) {
            return base.Channel.GetResByCusPhoneAsync(phone);
        }
    }
}
