//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerProject.CustomerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scheduler", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Scheduler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Hall HallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Movie MovieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MovieIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Reservation[] ReservationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Seat[] SeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> StarttimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datetime {
            get {
                return this.DatetimeField;
            }
            set {
                if ((this.DatetimeField.Equals(value) != true)) {
                    this.DatetimeField = value;
                    this.RaisePropertyChanged("Datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Hall Hall {
            get {
                return this.HallField;
            }
            set {
                if ((object.ReferenceEquals(this.HallField, value) != true)) {
                    this.HallField = value;
                    this.RaisePropertyChanged("Hall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HallID {
            get {
                return this.HallIDField;
            }
            set {
                if ((this.HallIDField.Equals(value) != true)) {
                    this.HallIDField = value;
                    this.RaisePropertyChanged("HallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Movie Movie {
            get {
                return this.MovieField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieField, value) != true)) {
                    this.MovieField = value;
                    this.RaisePropertyChanged("Movie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MovieID {
            get {
                return this.MovieIDField;
            }
            set {
                if ((this.MovieIDField.Equals(value) != true)) {
                    this.MovieIDField = value;
                    this.RaisePropertyChanged("MovieID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Reservation[] Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsField, value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchID {
            get {
                return this.SchIDField;
            }
            set {
                if ((this.SchIDField.Equals(value) != true)) {
                    this.SchIDField = value;
                    this.RaisePropertyChanged("SchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Seat[] Seats {
            get {
                return this.SeatsField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatsField, value) != true)) {
                    this.SeatsField = value;
                    this.RaisePropertyChanged("Seats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> Starttime {
            get {
                return this.StarttimeField;
            }
            set {
                if ((this.StarttimeField.Equals(value) != true)) {
                    this.StarttimeField = value;
                    this.RaisePropertyChanged("Starttime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hall", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Hall : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxNumberOfSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Scheduler[] SchedulersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HallID {
            get {
                return this.HallIDField;
            }
            set {
                if ((this.HallIDField.Equals(value) != true)) {
                    this.HallIDField = value;
                    this.RaisePropertyChanged("HallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxNumberOfSeats {
            get {
                return this.MaxNumberOfSeatsField;
            }
            set {
                if ((this.MaxNumberOfSeatsField.Equals(value) != true)) {
                    this.MaxNumberOfSeatsField = value;
                    this.RaisePropertyChanged("MaxNumberOfSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Scheduler[] Schedulers {
            get {
                return this.SchedulersField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulersField, value) != true)) {
                    this.SchedulersField = value;
                    this.RaisePropertyChanged("Schedulers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PlaytimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Scheduler[] SchedulersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieID {
            get {
                return this.MovieIDField;
            }
            set {
                if ((this.MovieIDField.Equals(value) != true)) {
                    this.MovieIDField = value;
                    this.RaisePropertyChanged("MovieID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Playtime {
            get {
                return this.PlaytimeField;
            }
            set {
                if ((this.PlaytimeField.Equals(value) != true)) {
                    this.PlaytimeField = value;
                    this.RaisePropertyChanged("Playtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Scheduler[] Schedulers {
            get {
                return this.SchedulersField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulersField, value) != true)) {
                    this.SchedulersField = value;
                    this.RaisePropertyChanged("Schedulers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Scheduler SchedulerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SchedulerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResID {
            get {
                return this.ResIDField;
            }
            set {
                if ((this.ResIDField.Equals(value) != true)) {
                    this.ResIDField = value;
                    this.RaisePropertyChanged("ResID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Row {
            get {
                return this.RowField;
            }
            set {
                if ((object.ReferenceEquals(this.RowField, value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Scheduler Scheduler {
            get {
                return this.SchedulerField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulerField, value) != true)) {
                    this.SchedulerField = value;
                    this.RaisePropertyChanged("Scheduler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SchedulerID {
            get {
                return this.SchedulerIDField;
            }
            set {
                if ((this.SchedulerIDField.Equals(value) != true)) {
                    this.SchedulerIDField = value;
                    this.RaisePropertyChanged("SchedulerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seat {
            get {
                return this.SeatField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatField, value) != true)) {
                    this.SeatField = value;
                    this.RaisePropertyChanged("Seat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seat", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Seat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Scheduler SchedulerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SchedulerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnArray {
            get {
                return this.ColumnArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnArrayField, value) != true)) {
                    this.ColumnArrayField = value;
                    this.RaisePropertyChanged("ColumnArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Scheduler Scheduler {
            get {
                return this.SchedulerField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulerField, value) != true)) {
                    this.SchedulerField = value;
                    this.RaisePropertyChanged("Scheduler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SchedulerID {
            get {
                return this.SchedulerIDField;
            }
            set {
                if ((this.SchedulerIDField.Equals(value) != true)) {
                    this.SchedulerIDField = value;
                    this.RaisePropertyChanged("SchedulerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServerProject.CustomerServiceReference.Reservation[] ReservationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CusID {
            get {
                return this.CusIDField;
            }
            set {
                if ((this.CusIDField.Equals(value) != true)) {
                    this.CusIDField = value;
                    this.RaisePropertyChanged("CusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerProject.CustomerServiceReference.Reservation[] Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsField, value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceReference.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllSchedulers", ReplyAction="http://tempuri.org/ICustomerService/GetAllSchedulersResponse")]
        ServerProject.CustomerServiceReference.Scheduler[] GetAllSchedulers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllSchedulers", ReplyAction="http://tempuri.org/ICustomerService/GetAllSchedulersResponse")]
        System.Threading.Tasks.Task<ServerProject.CustomerServiceReference.Scheduler[]> GetAllSchedulersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getSchedulerByMovie", ReplyAction="http://tempuri.org/ICustomerService/getSchedulerByMovieResponse")]
        ServerProject.CustomerServiceReference.Scheduler getSchedulerByMovie(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getSchedulerByMovie", ReplyAction="http://tempuri.org/ICustomerService/getSchedulerByMovieResponse")]
        System.Threading.Tasks.Task<ServerProject.CustomerServiceReference.Scheduler> getSchedulerByMovieAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getSchedulerByID", ReplyAction="http://tempuri.org/ICustomerService/getSchedulerByIDResponse")]
        ServerProject.CustomerServiceReference.Scheduler getSchedulerByID(int schedulerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getSchedulerByID", ReplyAction="http://tempuri.org/ICustomerService/getSchedulerByIDResponse")]
        System.Threading.Tasks.Task<ServerProject.CustomerServiceReference.Scheduler> getSchedulerByIDAsync(int schedulerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/makeReservation", ReplyAction="http://tempuri.org/ICustomerService/makeReservationResponse")]
        void makeReservation(string row, string seat, int schedulerID, int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/makeReservation", ReplyAction="http://tempuri.org/ICustomerService/makeReservationResponse")]
        System.Threading.Tasks.Task makeReservationAsync(string row, string seat, int schedulerID, int customerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : ServerProject.CustomerServiceReference.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<ServerProject.CustomerServiceReference.ICustomerService>, ServerProject.CustomerServiceReference.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServerProject.CustomerServiceReference.Scheduler[] GetAllSchedulers() {
            return base.Channel.GetAllSchedulers();
        }
        
        public System.Threading.Tasks.Task<ServerProject.CustomerServiceReference.Scheduler[]> GetAllSchedulersAsync() {
            return base.Channel.GetAllSchedulersAsync();
        }
        
        public ServerProject.CustomerServiceReference.Scheduler getSchedulerByMovie(int movieID) {
            return base.Channel.getSchedulerByMovie(movieID);
        }
        
        public System.Threading.Tasks.Task<ServerProject.CustomerServiceReference.Scheduler> getSchedulerByMovieAsync(int movieID) {
            return base.Channel.getSchedulerByMovieAsync(movieID);
        }
        
        public ServerProject.CustomerServiceReference.Scheduler getSchedulerByID(int schedulerID) {
            return base.Channel.getSchedulerByID(schedulerID);
        }
        
        public System.Threading.Tasks.Task<ServerProject.CustomerServiceReference.Scheduler> getSchedulerByIDAsync(int schedulerID) {
            return base.Channel.getSchedulerByIDAsync(schedulerID);
        }
        
        public void makeReservation(string row, string seat, int schedulerID, int customerID) {
            base.Channel.makeReservation(row, seat, schedulerID, customerID);
        }
        
        public System.Threading.Tasks.Task makeReservationAsync(string row, string seat, int schedulerID, int customerID) {
            return base.Channel.makeReservationAsync(row, seat, schedulerID, customerID);
        }
    }
}
